name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 12 * * 0,3,6' # Cada 3 días (lunes, jueves, domingo) a las 12:00

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: curl https://jvhqqbczfvbubqcwpxft.supabase.co
